# Austin Emmanuel Paulraj 20BAI1266

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
d=np.random.rand(10,4)
print(d)

[[0.40703747 0.12378501 0.79769296 0.36992532]
 [0.81146191 0.22765024 0.70091323 0.10346517]
 [0.13109917 0.10969028 0.82792391 0.17918751]
 [0.59192164 0.70813889 0.55277707 0.40167889]
 [0.60529595 0.54162115 0.28818651 0.58749762]
 [0.18378057 0.9078216  0.0321145  0.859856  ]
 [0.06312641 0.95176278 0.31976211 0.27067787]
 [0.21783881 0.81599638 0.3865311  0.88339467]
 [0.16648944 0.58120747 0.06446805 0.08897593]
 [0.99229477 0.41850443 0.85650986 0.28832238]]


In [ ]:
df=pd.DataFrame(d)
df.head()

0         1         2         3
0  0.407037  0.123785  0.797693  0.369925
1  0.811462  0.227650  0.700913  0.103465
2  0.131099  0.109690  0.827924  0.179188
3  0.591922  0.708139  0.552777  0.401679
4  0.605296  0.541621  0.288187  0.587498

In [ ]:
df.rename(columns = {0:'Random value 1',1:'Random value 2',2:'Random value 3',3:'Random value 4'}, inplace = True)
df.head()

Random value 1  Random value 2  Random value 3  Random value 4
0        0.407037        0.123785        0.797693        0.369925
1        0.811462        0.227650        0.700913        0.103465
2        0.131099        0.109690        0.827924        0.179188
3        0.591922        0.708139        0.552777        0.401679
4        0.605296        0.541621        0.288187        0.587498

In [ ]:
df.sum()

Random value 1    4.170346
Random value 2    5.386178
Random value 3    4.826879
Random value 4    4.032981
dtype: float64

In [ ]:
df.sum(1)

0    1.698441
1    1.843491
2    1.247901
3    2.254516
4    2.022601
5    1.983573
6    1.605329
7    2.303761
8    0.901141
9    2.555631
dtype: float64

In [ ]:
df.mean()

Random value 1    0.417035
Random value 2    0.538618
Random value 3    0.482688
Random value 4    0.403298
dtype: float64

In [ ]:
df.mean(1)

0    0.424610
1    0.460873
2    0.311975
3    0.563629
4    0.505650
5    0.495893
6    0.401332
7    0.575940
8    0.225285
9    0.638908
dtype: float64

In [ ]:
df.std()

Random value 1    0.319112
Random value 2    0.312995
Random value 3    0.309523
Random value 4    0.287463
dtype: float64

In [ ]:
df.std(1)

0    0.278679
1    0.347690
2    0.345191
3    0.126530
4    0.147437
5    0.452644
6    0.383441
7    0.324688
8    0.241233
9    0.338487
dtype: float64

In [ ]:
df.describe()

Random value 1  Random value 2  Random value 3  Random value 4
count       10.000000       10.000000       10.000000       10.000000
mean         0.417035        0.538618        0.482688        0.403298
std          0.319112        0.312995        0.309523        0.287463
min          0.063126        0.109690        0.032115        0.088976
25%          0.170812        0.275364        0.296080        0.202060
50%          0.312438        0.561414        0.469654        0.329124
75%          0.601952        0.789032        0.773498        0.541043
max          0.992295        0.951763        0.856510        0.883395

In [ ]:
df.isnull()

Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False
4           False           False           False           False
5           False           False           False           False
6           False           False           False           False
7           False           False           False           False
8           False           False           False           False
9           False           False           False           False

In [ ]:
df.dtypes

Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

In [ ]:
for i in range(10):
  print(df.loc[i][1:3])

Random value 2    0.123785
Random value 3    0.797693
Name: 0, dtype: float64
Random value 2    0.227650
Random value 3    0.700913
Name: 1, dtype: float64
Random value 2    0.109690
Random value 3    0.827924
Name: 2, dtype: float64
Random value 2    0.708139
Random value 3    0.552777
Name: 3, dtype: float64
Random value 2    0.541621
Random value 3    0.288187
Name: 4, dtype: float64
Random value 2    0.907822
Random value 3    0.032115
Name: 5, dtype: float64
Random value 2    0.951763
Random value 3    0.319762
Name: 6, dtype: float64
Random value 2    0.815996
Random value 3    0.386531
Name: 7, dtype: float64
Random value 2    0.581207
Random value 3    0.064468
Name: 8, dtype: float64
Random value 2    0.418504
Random value 3    0.856510
Name: 9, dtype: float64


In [ ]:
for i in range(10):
  print(df.iloc[i][1:3])

Random value 2    0.123785
Random value 3    0.797693
Name: 0, dtype: float64
Random value 2    0.227650
Random value 3    0.700913
Name: 1, dtype: float64
Random value 2    0.109690
Random value 3    0.827924
Name: 2, dtype: float64
Random value 2    0.708139
Random value 3    0.552777
Name: 3, dtype: float64
Random value 2    0.541621
Random value 3    0.288187
Name: 4, dtype: float64
Random value 2    0.907822
Random value 3    0.032115
Name: 5, dtype: float64
Random value 2    0.951763
Random value 3    0.319762
Name: 6, dtype: float64
Random value 2    0.815996
Random value 3    0.386531
Name: 7, dtype: float64
Random value 2    0.581207
Random value 3    0.064468
Name: 8, dtype: float64
Random value 2    0.418504
Random value 3    0.856510
Name: 9, dtype: float64


In [ ]:
!jupyter nbconvert --to html SmartInternzAIAssignments_1.ipynb

[NbConvertApp] Converting notebook SmartInternzAIAssignments_1.ipynb to html
[NbConvertApp] Writing 612142 bytes to SmartInternzAIAssignments_1.html
